/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desktopapp;

/**
 *
 * @author Dominik
 */
public class GuiDatabase extends javax.swing.JFrame {
    private Daemon daemon;
    /**
     * Creates new form GuiDatabase
     */
    public GuiDatabase() {
        initComponents();
        daemon = Daemon.getInstance();
        daemon.setLog(logArea);
        daemon.getClient().connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pullDbBtn = new javax.swing.JButton();
        logPanel = new javax.swing.JPanel();
        scrollPanel = new javax.swing.JScrollPane();
        logArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        logoutBtn = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        exitBtn = new javax.swing.JMenuItem();
        dataMb = new javax.swing.JMenu();
        addFbtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 420));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mainPanel.setAutoscrolls(true);
        mainPanel.setPreferredSize(new java.awt.Dimension(350, 400));
        mainPanel.setLayout(new java.awt.BorderLayout());

        pullDbBtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        pullDbBtn.setText("GET TO THE CHOPPA!");
        pullDbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pullDbBtnActionPerformed(evt);
            }
        });
        mainPanel.add(pullDbBtn, java.awt.BorderLayout.CENTER);

        logPanel.setPreferredSize(new java.awt.Dimension(400, 300));

        scrollPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPanel.setAutoscrolls(true);
        scrollPanel.setPreferredSize(new java.awt.Dimension(350, 300));

        logArea.setEditable(false);
        logArea.setColumns(20);
        logArea.setRows(5);
        logArea.setMaximumSize(new java.awt.Dimension(350, 200));
        scrollPanel.setViewportView(logArea);

        logPanel.add(scrollPanel);

        mainPanel.add(logPanel, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        logoutBtn.setText("Account");

        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        logoutBtn.add(jMenuItem1);

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        logoutBtn.add(exitBtn);

        jMenuBar1.add(logoutBtn);

        dataMb.setText("Data");

        addFbtn.setText("Add");
        addFbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFbtnActionPerformed(evt);
            }
        });
        dataMb.add(addFbtn);

        jMenuBar1.add(dataMb);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        disconnect();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void addFbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFbtnActionPerformed
      new GuiAdd().setVisible(true);
    }//GEN-LAST:event_addFbtnActionPerformed

    private void pullDbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pullDbBtnActionPerformed
        daemon.getClient().send(WSCommands.DATA);
    }//GEN-LAST:event_pullDbBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        disconnect();
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        //disconnect();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        disconnect();
    }//GEN-LAST:event_formWindowClosing

    
    private void disconnect(){
        daemon.getClient().close();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiDatabase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiDatabase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addFbtn;
    private javax.swing.JMenu dataMb;
    private javax.swing.JMenuItem exitBtn;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextArea logArea;
    private javax.swing.JPanel logPanel;
    private javax.swing.JMenu logoutBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton pullDbBtn;
    private javax.swing.JScrollPane scrollPanel;
    // End of variables declaration//GEN-END:variables
}
